import type { AppLocale } from "@/i18n/routing"

type Feature = { name: string; aurict: boolean; competitor: boolean }
type LocalizableComparison = { slug: string; title: string; description: string; tagline: string; differentiator?: string; ourStrengths: string[]; theirStrengths: string[]; features: Feature[] }

const phrases: Record<string, string> = {
  "Multiple AI providers": "Birden fazla yapay zekâ sağlayıcısı", "Multi-agent architecture": "Çoklu ajan mimarisi", "Auto-injected skills": "Otomatik eklenen beceriler", "Native compiled binary": "Yerel derlenmiş binary", "Windows support": "Windows desteği", "Bash command classifier": "Bash komut sınıflandırıcısı", "MCP integration": "MCP entegrasyonu", "Open source (AGPLv3)": "Açık kaynak (AGPLv3)", "Persistent memory": "Kalıcı bellek", "Terminal-native": "Terminal odaklı", "IDE-based": "IDE tabanlı", "Works over SSH": "SSH üzerinden çalışır", "Lightweight binary": "Hafif binary", "Inline suggestions": "Satır içi öneriler", "Open source": "Açık kaynak", "Sandbox execution": "Sandbox çalıştırma", "Git-focused workflow": "Git odaklı iş akışı", "Full coding assistant": "Tam kodlama asistanı", "No subscription fee": "Abonelik ücreti yok", "GitHub integration": "GitHub entegrasyonu", "Specialist agent architecture": "Uzman ajan mimarisi", "Contextual skills": "Bağlamsal beceriler", "Command safety controls": "Komut güvenlik kontrolleri", "Policy-oriented execution": "Politika odaklı çalıştırma", "Inline IDE suggestions": "Satır içi IDE önerileri", "9 AI providers": "9 yapay zekâ sağlayıcısı", "218+ skills": "218'den fazla beceri", "Bash classifier": "Bash sınıflandırıcısı",
}

const tr: Record<string, Omit<LocalizableComparison, "slug">> = {
  "claude-code": { title: "Aurict ve Claude Code", description: "Claude Code yalnızca Anthropic'e bağlıdır. Aurict 9 sağlayıcıyı, 9 uzman ajanı, 218'den fazla otomatik eklenen beceriyi destekler ve yerel binary olarak çalışır.", tagline: "Sağlayıcı esnekliği çoklu ajan gücüyle buluşuyor", differentiator: "Sağlayıcı esnekliği + çoklu ajan", ourStrengths: ["9 yapay zekâ sağlayıcısı — istediğiniz an geçiş, sağlayıcı bağımlılığı yok", "Paralel çalışan 9 uzman ajan", "218'den fazla otomatik eklenen bağlamsal beceri", "Yerel binary — Node.js çalışma zamanı gerekmez", "macOS, Linux ve Windows'ta çalışır", "Komut güvenliği için Bash sınıflandırıcısı", "MCP istemcisi — mevcut yapılandırmanızı kullanın"], theirStrengths: ["Sıkı Anthropic entegrasyonu", "Resmi Claude aracı"], features: [] },
  cursor: { title: "Aurict ve Cursor", description: "Cursor bir IDE'dir; Aurict bir terminal yapay zekâsıdır. Farklı yaklaşımlar, farklı güçlü yanlar: seçimi iş akışınıza göre yapın.", tagline: "Terminal odaklı ve IDE odaklı yaklaşım", differentiator: "Terminal ve IDE", ourStrengths: ["Her terminalde çalışır — IDE gerekmez", "Hafif yerel binary", "Çoklu ajan orkestrasyonu", "9 sağlayıcı, istediğiniz an geçiş", "218'den fazla bağlamsal beceri", "SSH dostu — uzak sunucularda çalışır"], theirStrengths: ["Görsel IDE deneyimi", "Satır içi kod önerileri", "Görsel diff görüntüleyici"], features: [] },
  aider: { title: "Aurict ve Aider", description: "Aider tek ajanlı, Git odaklı bir araçtır. Aurict ise çoklu sağlayıcı desteği ve bağlamsal becerilerle uzman ajanlar kullanır.", tagline: "Çoklu ajan ve tek ajan", differentiator: "Çoklu ajan + güvenlik", ourStrengths: ["Farklı görevler için 9 uzman ajan", "Tek sağlayıcıya bağlı olmayan 9 yapay zekâ sağlayıcısı", "218'den fazla bağlamsal beceri", "Güvenlik için Bash sınıflandırıcısı", "Korumalı terminal çalıştırması için politika sandbox'ı", "Tasarım ajanı sihirbazı", "Yerel Windows binary'si"], theirStrengths: ["Git entegrasyonu odağı", "Basit tek ajan yaklaşımı"], features: [] },
  "github-copilot": { title: "Aurict ve GitHub Copilot", description: "GitHub Copilot bir otomatik tamamlama aracıdır. Aurict, çoklu ajan orkestrasyonu ve derin kod tabanı anlayışı sunan tam bir yapay zekâ kodlama asistanıdır.", tagline: "Tam asistan ve otomatik tamamlama", differentiator: "Tam asistan + çoklu ajan", ourStrengths: ["Yalnızca otomatik tamamlama değil, tam kodlama asistanı", "9 uzman ajan", "9 yapay zekâ sağlayıcısı", "218'den fazla bağlamsal beceri", "Kod tabanı farkındalıklı bağlam", "Özel araçlar ve beceriler", "MCP entegrasyonu", "Zorunlu abonelik yok"], theirStrengths: ["Satır içi IDE önerileri", "GitHub ekosistemi entegrasyonu"], features: [] },
  opencode: { title: "Aurict ve OpenCode", description: "İki proje de açık kaynak terminal yapay zekâ iş akışlarını hedefler. Aurict uzman ajanlara, bağlamsal becerilere, güvenlik kontrollerine, mobil BYOK çalışmasına ve daha geniş bir ürün ekosistemine odaklanır.", tagline: "Zengin ajan çalışma zamanı ve minimal terminal yapay zekâsı", differentiator: "Beceriler + güvenlik + mobil", ourStrengths: ["Uzman ajanlar", "Birden fazla sağlayıcı", "Bağlamsal beceriler", "Komut güvenlik kontrolleri", "Politika odaklı çalıştırma", "Yerel Windows binary'si", "Mobil BYOK asistanı ve companion yönü"], theirStrengths: ["Minimal yaklaşım", "Daha küçük kapsam"], features: [] },
}

export function localizeComparison<T extends LocalizableComparison>(comparison: T, locale: AppLocale): T {
  if (locale !== "tr" || !tr[comparison.slug]) return comparison
  const translation = tr[comparison.slug]
  return { ...comparison, ...translation, features: comparison.features.map((feature) => ({ ...feature, name: phrases[feature.name] ?? feature.name })) }
}
